#!/bin/bash

# Use find command to search for all .gif files in the current directory and subdirectories
find . -type f -iname '*.gif' -exec sh -c '
  for file do
	      # Get the file name without the extension
	          filename=$(basename "$file")
		      filename_noext="${filename%.*}"
		          echo "$filename_noext"
			    done
			    ' sh {} + | LC_ALL=C sort -f

